### PR TITLE
Added Type Definitions

### PR DESCRIPTION
**Pull request by guytepper**
Added type definitions for `formatDuration` 

Thanks for the small yet useful library! :)

### CODE REVIEW

**Review by ungoldman — APPROVED** [review]
seems fine to me 🤷

**Comment by ungoldman** [comment]
@bcomnes I have successfully avoided getting slurped into the world of TypeScript maintenance so far. Any downsides to this? I know in the past other libraries have recommended maintaining types separately through some third party type definition aggregation library or something.

**Comment by bcomnes** [comment]
My only preference would be to use js-doc, unless this offers a speific-to-this-library advantage with the index.d.ts approach. That way you get the little poppy uppy docs in your ed and I think type checking.

**Comment by ungoldman** [comment]
@guytepper can you get the same mileage out of just modifying the main file to have the function definition in jsdoc?

**Comment by guytepper** [comment]
Sure, but I think it might result in a more complicated flow - [at least that's how it seems](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).

But I haven't done the jsdoc-to-ts approach before so I might be wrong here - @bcomnes have you ever done that?

**Comment by bcomnes** [comment]
Thats converting types. If types are defined in a module as a js-doc, TS should pick those up automatically without work. .d.ts definitely has more capabilities and features, but in the case of this module, we would not be using any of those.  Let me draft up an example (based on your work).

**Comment by bcomnes** [comment]
@guytepper Ok, I converted it over here https://github.com/hypermodules/format-duration/pull/6

I'm going to publish a beta version, would you be willing to test it out and let me know if it works (or doesn't work) to the level you expect?

**Comment by bcomnes** [comment]
@ungoldman can you give me publish rights on npm? I'm going to try this out as a beta

**Comment by ungoldman** [comment]
@bcomnes you should be added now!

**Comment by ungoldman** [comment]
lol wait!!!!

look at this: https://www.npmjs.com/package/@types/format-duration

**Comment by ungoldman** [comment]
Screen Shot 2021-07-13 at 1 43 08 PM

**Comment by ungoldman** [comment]
I knew this sounded familiar https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21893

**Comment by bcomnes** [comment]
I think thats the workaround people have to install additionally if they want types.

**Comment by guytepper** [comment]
yup, I'd prefer to not install an additional package for getting types :)

ready to report once the beta gets released!

**Comment by bcomnes** [comment]
Ok, I published a beta tag (`1.3.2-beta.0`) @guytepper can you let me know if that works for you?

**Comment by guytepper** [comment]
It doesn't seem to be working, the type declarations are not found. You can see an example [here](https://codesandbox.io/s/flamboyant-christian-2po5t?file=/src/index.ts)

**Comment by bcomnes** [comment]
K, gonna play around with it.

**Comment by bcomnes** [comment]
Just messed up and accidentally published on the latest channel. I wen't ahead and republished a version ahead since you can't unpublish on npm any more. Sorry for the noise, npm is unforgiving if you hit enter too early.

**Comment by bcomnes** [comment]
Ok, so I did a little bit of digging to finally figure this out. 

So TS doesn't actually consume JSDoc strings from node_modules, because of performance or reasons. But you can author a typed module from JSDoc strings, you just need to adopt the ts toolchain and add a build step. @voxpelli wrote a great article on this method:

https://voxpelli.com/2019/10/use-type-script-3-7-to-generate/

I don't want to do that here. What I would be fine with:

- Landing this and just calling it good. Yay for doccy poppy uppys. 

or 

- Be a conservative maintainer and just declare that types are not really going to help anyone with a function this small, and that if you really want types just use [automaticTypeAquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition). (that isn't to say I don't appreciate your time and effort @guytepper, I do, thank you)

@ungoldman your call. 

Glad to have finally figured this question I had out about the usefulness of JSDocs though.

**Comment by guytepper** [comment]
Thanks for that information. 

In that case I wonder why not to go with the `index.d.ts` method - isn't it better than not having types at all?  

I'm using this function frequently in a project and it'd be nice to have the benefits TS provides

**Comment by ungoldman** [comment]
@bcomnes I don't feel strongly either way. if you both want to just merge and call it good I'm fine with that.

**Comment by bcomnes** [comment]
OK we can just land this then.

**Comment by ungoldman** [comment]
released as 1.4.0

**Pull request merged**
